/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAboutContent' : ActorMethod<
    [],
    { 'title' : string, 'name' : string, 'summary' : string }
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [{ 'name' : string }]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCertifications' : ActorMethod<[], Array<string>>,
  'getContactInfo' : ActorMethod<
    [],
    { 'linkedin' : string, 'email' : string, 'location' : string }
  >,
  'getEducation' : ActorMethod<
    [],
    { 'description' : string, 'degree' : string, 'years' : string }
  >,
  'getExperience' : ActorMethod<
    [],
    Array<
      {
        'period' : string,
        'description' : string,
        'company' : string,
        'position' : string,
      }
    >
  >,
  'getProjectDetails' : ActorMethod<
    [string],
    [] | [
      {
        'id' : string,
        'title' : string,
        'role' : string,
        'description' : string,
        'videoUrl' : string,
      }
    ]
  >,
  'getProjectVideos' : ActorMethod<[], Array<[string, string]>>,
  'getProjects' : ActorMethod<[], Array<[string, string]>>,
  'getSkills' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [{ 'name' : string }]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[{ 'name' : string }], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];